# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CS3STHLM
email: 
description:
  CS3STHLM - Stockholm international summit on cyber-security in SCADA and Industrial Control Systems.
  CS3STHLM is an annual summit that gather the most important ICS/SCADA cyber security stakeholders
  across critical industries (i.e. energy, oil & gas, water, transportation and smartgrid etc)
baseurl: ""
url:

# Build settings
markdown: kramdown
theme:

gems:
  - jekyll-sitemap