---
title: CS3STHLM
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: CS3sthlm, the premier Cyber Security Conference for ICS/SCADA and Critical Infrastructure, annually in October with pre-summit Trainings and Expo.
baseurl: ''
url: 
markdown: kramdown
theme: 
include:
- _pages

sass:
  sourcemap: never
  style: compressed
