---
title: CS3STHLM
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: CS3STHLM - Stockholm international summit on cyber-security in SCADA
  and Industrial Control Systems. CS3STHLM is an annual summit that gather the most
  important ICS/SCADA cyber security stakeholders across critical industries (i.e.
  energy, oil & gas, water, transportation and smartgrid etc)
baseurl: ''
url: 
markdown: kramdown
theme: 
include:
- _pages
plugins:
- jekyll-sitemap
- jekyll-seo-tag
